server:
  port: "90"


datasource:
  host: "sgp-info-svc.csntzsasnlad.us-east-1.rds.amazonaws.com:3306"
  user: "sgpinfosvc"
  pass: "test1234"
  dbname: "sgp_info_svc"

paths:
  createConmorbility: "/v1/sgp-logic-svc/createConmorbility"
  updateConmorbility: "/v1/pr-logic-svc/updateConmorbility"
  deleteConmorbility: "/v1/pr-logic-svc/deleteConmorbility"

appProperties:
  createConmorbilityStatusInitial: 1
  deleteConmorbilityStatusInactive: 2