server:
  port: "92"


datasource:
  host: "localhost:3306"
  user: "root"
  pass: "1234"
  dbname: "sgp_info_svc"

paths:
  createComorbidity: "/v1/sgp-logic-svc/createComorbidity"
  createSymptom: "/v1/sgp-logic-svc/createSymptom"
  createInfoPatient: "/v1/sgp-logic-svc/createInfoPatient"

  updateComorbidity: "/v1/sgp-logic-svc/updateComorbidity"
  updateSymptom: "/v1/sgp-logic-svc/updateSymptom"
  updateInfoPatient: "/v1/sgp-logic-svc/updateInfoPatient"

  deleteComorbidity: "/v1/sgp-logic-svc/deleteComorbidity"
  deleteSymptom: "/v1/sgp-logic-svc/deleteSymptom"

appProperties:
  createComorbidityStatusInitial: 1
  deleteComorbidityStatusInactive: 2