server:
  port: "90"


datasource:
  host: "localhost:3306"
  user: "root"
  pass: "12345"
  dbname: "sgp_info_svc"

paths:
  createComorbidity: "/v1/sgp-logic-svc/createComorbidity"
  updateComorbidity: "/v1/sgp-logic-svc/updateComorbidity"
  deleteComorbidity: "/v1/sgp-logic-svc/deleteComorbidity"

appProperties:
  createComorbidityStatusInitial: 1
  deleteComorbidityStatusInactive: 2